### ISSUE TITLE
您好 我的这个运行显示路径错误  可以帮我看一下啥问题吗

### ISSUE THREAD

**Issue by shao639** [sivanWu0222/GraduationProject#2]
Traceback (most recent call last):
  File "D:/GraduationProject-master/GraduationDesign/SSFN_V1/main.py", line 6, in <module>
    ssf.init(Sen1, Sen2)
  File "D:\GraduationProject-master\GraduationDesign\SSFN_V1\SSF_V1.py", line 45, in init
    Sen1_word_vec_set = util.get_sen_vec_set(Sen1_word)
  File "D:\GraduationProject-master\GraduationDesign\SSFN_V1\util.py", line 54, in get_sen_vec_set
    vec_set.append(get_wrod_vec(word))
  File "D:\GraduationProject-master\GraduationDesign\SSFN_V1\util.py", line 29, in get_wrod_vec
    with open(get_file_path(), 'r', encoding='utf-8') as file:
  File "D:\GraduationProject-master\GraduationDesign\SSFN_V1\util.py", line 14, in get_file_path
    file_path = content_dict['path']
KeyError: 'path'

**Comment by sivanWu0222** [comment]
请认真阅读**README.md**文档中的项目运行部分，尤其第2步中的数据集以及预训练模型的路径，如果加载不到就会出现这个错误
